# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combnGenElem <- function(xv, nv, kv) {
    .Call('ultraCombo_combnGenElem', PACKAGE = 'ultraCombo', xv, nv, kv)
}

revCombnGenElem <- function(xv, nv) {
    .Call('ultraCombo_revCombnGenElem', PACKAGE = 'ultraCombo', xv, nv)
}

