# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combnGenElem_numeric <- function(xv, nv, kv) {
    .Call('ultraCombo_combnGenElem_numeric', PACKAGE = 'ultraCombo', xv, nv, kv)
}

combnGenElem_integer <- function(xv, nv, kv) {
    .Call('ultraCombo_combnGenElem_integer', PACKAGE = 'ultraCombo', xv, nv, kv)
}

revCombnGenElem_integer <- function(xv, nv) {
    .Call('ultraCombo_revCombnGenElem_integer', PACKAGE = 'ultraCombo', xv, nv)
}

revCombnGenElem_numeric <- function(xv, nv) {
    .Call('ultraCombo_revCombnGenElem_numeric', PACKAGE = 'ultraCombo', xv, nv)
}

