# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

combnGenElemC <- function(xv, nv, kv, chv) {
    .Call('ultraCombo_combnGenElemC', PACKAGE = 'ultraCombo', xv, nv, kv, chv)
}

revCombnGenElemC <- function(xv, nv) {
    .Call('ultraCombo_revCombnGenElemC', PACKAGE = 'ultraCombo', xv, nv)
}

