// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// combnGenElem
IntegerVector combnGenElem(NumericVector xv, IntegerVector nv, IntegerVector kv);
RcppExport SEXP ultraCombo_combnGenElem(SEXP xvSEXP, SEXP nvSEXP, SEXP kvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xv(xvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kv(kvSEXP);
    rcpp_result_gen = Rcpp::wrap(combnGenElem(xv, nv, kv));
    return rcpp_result_gen;
END_RCPP
}
// revCombnGenElem
NumericVector revCombnGenElem(IntegerVector xv, IntegerVector nv);
RcppExport SEXP ultraCombo_revCombnGenElem(SEXP xvSEXP, SEXP nvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xv(xvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nv(nvSEXP);
    rcpp_result_gen = Rcpp::wrap(revCombnGenElem(xv, nv));
    return rcpp_result_gen;
END_RCPP
}
