// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// combnGenElemRcpp
IntegerVector combnGenElemRcpp(NumericVector xv, IntegerVector nv, IntegerVector kv, NumericVector chv);
RcppExport SEXP ultraCombo_combnGenElemRcpp(SEXP xvSEXP, SEXP nvSEXP, SEXP kvSEXP, SEXP chvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type xv(xvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type kv(kvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type chv(chvSEXP);
    rcpp_result_gen = Rcpp::wrap(combnGenElemRcpp(xv, nv, kv, chv));
    return rcpp_result_gen;
END_RCPP
}
// revCombnGenElemRcpp
NumericVector revCombnGenElemRcpp(IntegerVector xv, IntegerVector nv);
RcppExport SEXP ultraCombo_revCombnGenElemRcpp(SEXP xvSEXP, SEXP nvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type xv(xvSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type nv(nvSEXP);
    rcpp_result_gen = Rcpp::wrap(revCombnGenElemRcpp(xv, nv));
    return rcpp_result_gen;
END_RCPP
}
